/** Declarative ERP module catalog. Core POS modules stay bundled so existing stores keep working. */

export const MODULE_STATUS = {
  AVAILABLE: "available",
  INSTALLED: "installed",
  ARCHIVED: "archived",
};

export const MODULE_LIFECYCLE = {
  CORE: "core",
  BUNDLED: "bundled",
  OPTIONAL: "optional",
};

export const MODULE_CATALOG = [
  {
    id: "core",
    name: "Core",
    description: "Authentication, database, navigation, and the module manager.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.CORE,
    category: "core",
    dependencies: [],
    defaultEnabled: true,
    showInManager: false,
    showInPermissions: false,
    uninstallable: false,
    disableable: false,
  },
  {
    id: "users",
    name: "Users",
    description: "Administrators, cashiers, roles, and subscriptions.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.CORE,
    category: "core",
    dependencies: [],
    defaultEnabled: true,
    adminOnly: true,
    showInManager: false,
    showInPermissions: true,
    uninstallable: false,
    disableable: false,
  },
  {
    id: "settings",
    name: "Settings",
    description: "Store configuration, backups, and system settings.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.CORE,
    category: "core",
    dependencies: [],
    defaultEnabled: true,
    adminOnly: true,
    showInManager: false,
    showInPermissions: true,
    uninstallable: false,
    disableable: false,
  },
  {
    id: "dashboard",
    name: "Dashboard",
    description: "Home dashboard, daily board, and store stats.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.BUNDLED,
    category: "core",
    dependencies: [],
    defaultEnabled: true,
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
  },
  {
    id: "sales",
    name: "Sales",
    description: "POS checkout, retail invoices, holds, returns, and customer collections.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.BUNDLED,
    category: "erp",
    dependencies: [],
    defaultEnabled: true,
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
  },
  {
    id: "products",
    name: "Products",
    description: "Catalog, categories, units, barcodes, and pricing.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.BUNDLED,
    category: "erp",
    dependencies: [],
    defaultEnabled: true,
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
  },
  {
    id: "inventory",
    name: "Inventory",
    description: "Stock on hand, movements, adjustments, and valuation.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.BUNDLED,
    category: "erp",
    dependencies: ["products"],
    defaultEnabled: true,
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
  },
  {
    id: "customers",
    name: "Customers",
    description: "Customer profiles, credit limits, receivables, and statements.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.BUNDLED,
    category: "erp",
    dependencies: [],
    defaultEnabled: true,
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
  },
  {
    id: "suppliers",
    name: "Suppliers",
    description: "Supplier profiles, payables, and supplier statements.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.BUNDLED,
    category: "erp",
    dependencies: [],
    defaultEnabled: true,
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
  },
  {
    id: "purchasing",
    name: "Purchasing",
    description: "Purchase invoices, credit purchases, and supplier payments.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.BUNDLED,
    category: "erp",
    dependencies: ["suppliers", "inventory"],
    defaultEnabled: true,
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
  },
  {
    id: "reports",
    name: "Reports",
    description: "Sales, purchase, inventory, and daily close reports.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.BUNDLED,
    category: "erp",
    dependencies: ["sales"],
    defaultEnabled: true,
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
  },
  {
    id: "zatca",
    name: "ZATCA",
    description: "Saudi e-invoicing (Phase 1 QR and Phase 2 XML sync). Does not replace the existing ZATCA engine.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.BUNDLED,
    category: "compliance",
    dependencies: ["sales"],
    defaultEnabled: true,
    settingsTab: "zatca",
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
  },
  {
    id: "accounting",
    name: "Accounting",
    description: "Double-entry books, chart of accounts, journals, and financial reports.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.OPTIONAL,
    category: "erp",
    dependencies: ["sales", "purchasing", "inventory"],
    childModules: ["expenses", "partners", "cash_bank"],
    defaultEnabled: false,
    settingsTab: "accounting",
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
    hasFinancialData: true,
    installHandler: "accounting",
    dataTables: ["journal_entries", "journal_lines", "accounts", "account_groups", "fiscal_periods"],
  },
  {
    id: "expenses",
    name: "Expenses",
    description: "Operating expenses, categories, VAT, and payment methods.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.OPTIONAL,
    category: "erp",
    dependencies: ["accounting"],
    defaultEnabled: false,
    settingsTab: "accounting",
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
    hasFinancialData: true,
    dataTables: ["expenses", "expense_categories"],
  },
  {
    id: "partners",
    name: "Partners",
    description: "Partner capital, drawings, loans, ownership, and equity ledger.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.OPTIONAL,
    category: "erp",
    dependencies: ["accounting"],
    defaultEnabled: false,
    settingsTab: "accounting",
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
    hasFinancialData: true,
    dataTables: ["partners", "partner_transactions"],
  },
  {
    id: "cash_bank",
    name: "Cash & Bank",
    description: "Cash and bank accounts, receive, pay, transfers, and ledgers.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.OPTIONAL,
    category: "erp",
    dependencies: ["accounting"],
    defaultEnabled: false,
    settingsTab: "accounting",
    showInManager: true,
    showInPermissions: true,
    uninstallable: false,
    disableable: true,
    hasFinancialData: true,
  },
  {
    id: "wholesale",
    name: "Wholesale",
    description: "Bulk price lists for shops and distributors. Retail POS prices stay the same.",
    version: "1.0.0",
    lifecycle: MODULE_LIFECYCLE.OPTIONAL,
    category: "erp",
    dependencies: ["sales", "inventory", "customers"],
    defaultEnabled: false,
    settingsTab: "modules",
    showInManager: true,
    showInPermissions: true,
    uninstallable: true,
    disableable: true,
    hasFinancialData: false,
    installHandler: "wholesale",
    dataTables: ["price_lists", "price_list_items", "customer_price_lists", "product_units"],
  },
];

const BY_ID = new Map(MODULE_CATALOG.map((mod) => [mod.id, mod]));

export function getCatalogModule(moduleId) {
  return BY_ID.get(moduleId) || null;
}

export function getManagerModules() {
  return MODULE_CATALOG.filter((mod) => mod.showInManager);
}

export function getPermissionModules() {
  return MODULE_CATALOG.filter((mod) => mod.showInPermissions && !mod.adminOnly);
}

export function getAdminPermissionModules() {
  return MODULE_CATALOG.filter((mod) => mod.showInPermissions && mod.adminOnly);
}

export function getChildModules(moduleId) {
  return getCatalogModule(moduleId)?.childModules || [];
}
