/** Grouped sidebar navigation — daily shop work first, setup last. */

export const NAV_SECTIONS = {
  shop: "Shop",
  buying: "Buying",
  money: "Money",
  setup: "Setup",
};

export const NAV_GROUPS = [
  {
    id: "dashboard",
    label: "Home",
    icon: "LayoutDashboard",
    path: "/",
    module: "dashboard",
    section: "shop",
  },
  {
    id: "pos",
    label: "POS",
    icon: "ShoppingCart",
    path: "/sales",
    module: "sales",
    section: "shop",
    featured: true,
  },
  {
    id: "sales",
    label: "Sales",
    icon: "ClipboardList",
    module: "sales",
    section: "shop",
    items: [
      { id: "orders", path: "/orders", label: "Invoices" },
      { id: "zatca-sync", path: "/zatca-sync", label: "E-invoices" },
    ],
  },
  {
    id: "products",
    label: "Catalog",
    icon: "Package",
    module: "products",
    section: "shop",
    items: [
      { id: "products-list", path: "/products", label: "Products" },
      { id: "stock", path: "/inventory", label: "Stock", module: "inventory" },
      { id: "categories", path: "/categories", label: "Categories" },
      { id: "units", path: "/units", label: "Units" },
    ],
  },
  {
    id: "customers",
    label: "Customers",
    icon: "Users",
    path: "/customers",
    module: "customers",
    section: "shop",
  },
  {
    id: "purchasing",
    label: "Purchases",
    icon: "Truck",
    module: "purchasing",
    section: "buying",
    items: [
      { id: "purchases", path: "/purchases", label: "Purchases" },
      { id: "supplier-accounts", path: "/suppliers", label: "Suppliers", module: "suppliers" },
    ],
  },
  {
    id: "wholesale",
    label: "Wholesale",
    icon: "Store",
    path: "/wholesale",
    module: "wholesale",
    section: "buying",
  },
  {
    id: "cash",
    label: "Cash",
    icon: "Wallet",
    module: "cash_bank",
    section: "money",
    items: [
      { id: "cash-receive", path: "/accounting/receive", label: "Receive", module: "cash_bank" },
      { id: "cash-pay", path: "/accounting/pay", label: "Pay", module: "cash_bank" },
      { id: "expenses", path: "/accounting/expenses", label: "Expenses", module: "expenses" },
      { id: "daily-close", path: "/daily-close", label: "Daily close", module: "reports", icon: "CalendarCheck" },
    ],
  },
  {
    id: "accounting",
    label: "Accounting",
    icon: "BookOpen",
    module: "accounting",
    section: "money",
    items: [
      { id: "journals", path: "/accounting/journals", label: "Books", module: "accounting" },
      { id: "partners", path: "/accounting/partners", label: "Partners", module: "partners" },
      { id: "employees", path: "/employees", label: "Employees", module: "expenses" },
    ],
  },
  {
    id: "reports",
    label: "Reports",
    icon: "BarChart3",
    path: "/reports",
    module: "reports",
    section: "money",
  },
  {
    id: "administration",
    label: "Setup",
    icon: "Settings",
    module: "settings",
    section: "setup",
    items: [
      { id: "settings", path: "/settings", label: "Settings", module: "settings" },
      { id: "users", path: "/users", label: "Users", module: "users" },
      { id: "subscriptions", path: "/subscriptions", label: "Subscriptions", module: "users" },
      { id: "store-cards", path: "/store-cards", label: "Store card", module: "settings" },
      { id: "cloud-backup", path: "/cloud-backup", label: "Backup", module: "settings" },
      { id: "zatca-queue", path: "/zatca-queue", label: "ZATCA queue", module: "settings" },
      { id: "zatca-test", path: "/zatca-test", label: "ZATCA test", module: "settings" },
    ],
  },
];
